### ISSUE TITLE
似乎存储型xss检测效果不好

### ISSUE THREAD

**Issue by 3xp10it** [bsmali4/xssfork#11]
本地搭建dvwa,设置lever为low后尝试检测post存储型xss
http://192.168.43.190/dvwa/vulnerabilities/xss_s/
`python2 xssfork.py -u "http://192.168.43.190/dvwa/vulnerabilities/xss_s/" --data="txtName=a&mtxMessage=b&btnSign=Sign+Guestbook" --cookie "PHPSESSID=ht4fjel6rpta7qbfibksr3ao80;security=low"  -m heavy`
使用上面的命令没有检测出来,后换成xssforkapi.py的添加任务方式也没检测出来,不知这里可有改进?

**Comment by bsmali4** [comment]
我记得，dvwa发包是要带csrftoken的，还有的话，存储型的必须指定一个输出点

**Comment by 3xp10it** [comment]
lever为low是没有token的,用xssforkapi.py添加任务方式检测时有指定输出点(输出点为相同页面),目前没有检测出来.

**Comment by bsmali4** [comment]
这个，我最近也发现了，准备花个时间好好看看
