### ISSUE TITLE
requestment.txt -> requirements.txt

### ISSUE THREAD

**Issue by 3xp10it** [bsmali4/xssfork#16]
根目录下requestment.txt -> requirements.txt?

**Comment by bsmali4** [comment]
嗯，好吧，不纠结这个，感谢我大哥提醒

**Comment by 3xp10it** [comment]
测试dvwa时发现无法成功检测,在macOS和kali上均测试过(测试时设置了dvwa的level的等级为low,使用kali自带的xss检测工具`xsser`测试dvwa的xss时可成功检测到)

**Comment by bsmali4** [comment]
我擦，不科学啊，周六解决掉。
