### ISSUE TITLE
关于请求方法和payload问题

### ISSUE THREAD

**Issue by d4wner** [bsmali4/xssfork#18]
RT，作者的项目简单看了下很棒，但鄙人这里有两个小问题：
```
1.只加-u参数，每次payload在890/1527就卡住了，换了好几个站都这样，不知道是否鄙人使用方法有错。
2.似乎您只采用了phantomjs，没采用selenium？想请教下您这里是如何支持post方法的，是否能检测referer之类的参数。
```
就个人所得，光依靠JS本身，似乎不能带上非w3g所规定的非安全因素【如referer】发送数据包，望指教如何解决。

**Comment by bsmali4** [comment]
现在这个项目有点老了，我准备换成chrome-less,请耐心等待。phantomjs卡住问题之前修复过了，这个项目暂时不会继续维护了，后面我会新启一个项目。

**Comment by bsmali4** [comment]
-u '',必须包含''

**Comment by bsmali4** [comment]
phantomjs 原声api就是js的，selenium你可以理解成一个通用的中转，最后还是会用原声api的。所以我直接干脆用了官方api

**Comment by d4wner** [comment]
wow，-u参数肯定后面加了url的，这个应该还不会弄错。
另外，想请教下官方api是直接支持post方法的么，是否能检测referer之类的参数？
