### ISSUE TITLE
 cannot import name 'XSS_FORK_PATH'

### ISSUE THREAD

**Issue by childeYin** [bsmali4/xssfork#6]
when I use this on my mac , 
       `python3.5 xssfork.py -u=http://....`
it report some errors,
```
Traceback (most recent call last):
  File "xssfork.py", line 12, in <module>

    from common import log

  File "/private/var/www/xssfork/common/__init__.py", line 11, in <module>

    from taskschedule.task_schedule import CompletePacket

  File "/private/var/www/xssfork/common/../taskschedule/__init__.py", line 13, in <module>

    from common import log

  File "/private/var/www/xssfork/common/log.py", line 9, in <module>

    from path import XSS_FORK_PATH

ImportError: cannot import name 'XSS_FORK_PATH'
```

**Comment by bsmali4** [comment]
麻烦，python路径

**Comment by childeYin** [comment]
我打印的你写入sys.path 之后的数据，
```
[
'/private/var/www/xssfork/common/../', 
'/private/var/www/xssfork', '/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python35.zip', 
'/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5', 
'/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin', 
'/usr/local/Cellar/python3/3.5.0/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload', 
'/usr/local/lib/python3.5/site-packages'
]
```

**Comment by bsmali4** [comment]
先在解决了吗

**Comment by childeYin** [comment]
解决问题：
```
1. no module path

    pip install path

2.can’t find XSS_FORK_PATH

    fix common/__init__.py

        XSS_FORK_PATH = "{}/../".format(os.path.dirname(os.path.abspath(__file__)))

    to
        XSS_FORK_PATH = "{}/".format(os.path.dirname(os.path.abspath(__file__)))

```
目前还没通, 是因为缺各种模块，我很少用python，现在网络也不好，我晚上回家试一下。目前我不确定我的这种改法是不是有其他的迁移问题出现，可以等我，完全解决好了之后，我把我这种小白遇到的问题解决方案发出来，就关掉这个帖子。或者直接您直接关掉也可以。

**Comment by childeYin** [comment]
额，不好意思 ，我现在还没有安装上pyside ,我mac上的python是3.5， 然后目前安装pyside各种报错，
直接
pip install pyside  报错， 版本不支持
 
         error:
                  only these python versions are supported: [(2, 6), (2, 7), (3, 2), (3, 3), (3, 4)]， 
              Command "python setup.py egg_info" failed with error code 1 

用pyside-setup安装的时候，报错

   python setup.py build  --qmake=/usr/local/Cellar/qt/5.9.1/bin/qmake  --openssl=/usr/bin/openssl --build-tests --ignore-git --jobs=4

    errors:
        LLVM version 3.9 is required (llvm-config detected /bin/sh: llvm-config:
        command not found at /bin/sh: llvm-config: command not found).`

**Comment by bsmali4** [comment]
对，最好是python2.7，我开发环境是这个，3.5的很多函数名可能变了

**Comment by childeYin** [comment]
系统上的pip 昨天升级到了3.5, 本来我是两个 2.7 和3.5共存的，结果昨天弄没了2.7，我后来跑到 print sql 报语法错误， 确信了是我的版本和你的应该是不一致的，路径问题很明显， 上边的改过之后，继续下走，出现了迁移出来的路径问题，感觉同级目录的__init__.py并没有有用，我在看一下，顺便切个版本，对python了解的不多，不好意思，麻烦你了。
