### ISSUE TITLE
大哥你的这个检测貌似不行

### ISSUE THREAD

**Issue by harris2015** [bsmali4/xssfork#7]
明明有xss的 payload=%3C/script%3E%3Ca%20onmouseover=prompt(65534)%3Exxs%20link%3C/a%3E  检测不出来

**Comment by harris2015** [comment]
document.getElementsByTagName("xss").length; 应该是这句检测不到新出现的元素

**Comment by bsmali4** [comment]
有两个函数啊，一个是hook新元素，另外一个是hook prompt,alert这种事件的触发，两个只要触发一个就表示有xss

**Comment by bsmali4** [comment]
至于您说的不行，我觉得如果可以的华，最好拿具体环境给我测试下，对了如果你是linux的话， 有个命名的问题是不行的，我今天把bug修复下，更新下代码。

**Comment by bsmali4** [comment]
刚刚把linux的问题修复了，你可以继续试下

**Comment by harris2015** [comment]
我是windows环境。。。弹窗那个没问题  主要是新元素的hook的好像不太对 返回的为0  getElementsByTagName("xss")  -》 字符串xss好像要根据具体情况改

**Comment by bsmali4** [comment]
默认payload检测的时候会创建<xss>标签

**Comment by harris2015** [comment]
我用你创建的默认payload跑的 </script><a onmouseover="alert(65534)">xxs link</a>//  这个payload

**Comment by harris2015** [comment]
额 好像我弄错了  这个应该是事件需要触发 不是新建标签

**Comment by bsmali4** [comment]
对啊，新建标签这类payload其实 xssforkapi 的首先检测规则,因为这类标签比较少，加载起来快。

**Comment by harris2015** [comment]
恩 那就是事件触发那里有点问题

**Comment by harris2015** [comment]
Element.prototype.addEventListener = function(a,b,c) {
            EVENT_LIST.push({"event": event, "element": this});
            _addEventListener.apply(this, arguments);
        };
